all: compile

compile: main.o basic.o Interpolation.o Grid.o functions.o Lagrange.o
	g++ -g main.o basic.o Interpolation.o Grid.o functions.o Lagrange.o

main.o: main.cpp
	g++ -g -c main.cpp

basic.o: basic.cpp
	g++ -g -c basic.cpp

Interpolation.o: Interpolation.cpp
	g++ -g -c Interpolation.cpp

Grid.o: Grid.cpp
	g++ -g -c Grid.cpp

functions.o: functions.cpp
	g++ -g -c functions.cpp

Lagrange.o: Lagrange.cpp
	g++ -g -c Lagrange.cpp

clean:
	rm -rf *.o compile
